development:
  adapter: postgresql
  encoding: unicode
  database: recipes_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: recipes_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password:
